---
- hosts: all
  tasks:
    - name: Check file existence
      block:
        - stat:
            path: //home/ansible/lab-error-handling/transaction_list
          register: result
        - debug: msg="File exists!"
      