---
- name: Check if a file exists
  hosts: all
  gather_facts: false

  tasks:
    - name: Check file existence
      stat:
        path: /home/ansible/lab-error-handling/transaction_list
      register: result
    - debug: msg="File exists!"
      